language: python
python:
  - '3.7'
install:
  - pip install sphinx sphinx_rtd_theme
  - pip install -r requirements.txt
script:
  - make html

  - touch _build/html/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/
